/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/About': RouteRecordInfo<'/About', '/About', Record<never, never>, Record<never, never>>,
    '/Contact': RouteRecordInfo<'/Contact', '/Contact', Record<never, never>, Record<never, never>>,
    '/FAQ': RouteRecordInfo<'/FAQ', '/FAQ', Record<never, never>, Record<never, never>>,
    '/portfolio/': RouteRecordInfo<'/portfolio/', '/portfolio', Record<never, never>, Record<never, never>>,
    '/portfolio/BanffLogCabin': RouteRecordInfo<'/portfolio/BanffLogCabin', '/portfolio/BanffLogCabin', Record<never, never>, Record<never, never>>,
    '/portfolio/Components': RouteRecordInfo<'/portfolio/Components', '/portfolio/Components', Record<never, never>, Record<never, never>>,
    '/portfolio/PersonalProject': RouteRecordInfo<'/portfolio/PersonalProject', '/portfolio/PersonalProject', Record<never, never>, Record<never, never>>,
  }
}
