/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'Justin Shaw': RouteRecordInfo<'Justin Shaw', '/', Record<never, never>, Record<never, never>>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    'About': RouteRecordInfo<'About', '/about', Record<never, never>, Record<never, never>>,
    'Contact': RouteRecordInfo<'Contact', '/contact', Record<never, never>, Record<never, never>>,
    'FAQ': RouteRecordInfo<'FAQ', '/faq', Record<never, never>, Record<never, never>>,
    'portfolio': RouteRecordInfo<'portfolio', '/portfolio', Record<never, never>, Record<never, never>>,
    'blc': RouteRecordInfo<'blc', '/portfolio/banfflogcabin', Record<never, never>, Record<never, never>>,
    'Components': RouteRecordInfo<'Components', '/portfolio/components', Record<never, never>, Record<never, never>>,
    'Personal Project': RouteRecordInfo<'Personal Project', '/portfolio/personalproject', Record<never, never>, Record<never, never>>,
  }
}
